- name: Deploy eCommerce Store
  hosts: web
  become: yes
  tasks:
    - name: Pull backend Docker image
      docker_image:
        name: "{{ docker_username }}/ecom-backend"
        source: pull

    - name: Pull frontend Docker image
      docker_image:
        name: "{{ docker_username }}/ecom-frontend"
        source: pull

    - name: Stop and remove existing backend container
      docker_container:
        name: backend
        state: absent

    - name: Stop and remove existing frontend container
      docker_container:
        name: frontend
        state: absent

    - name: Start backend container
      docker_container:
        name: backend
        image: "{{ docker_username }}/ecom-backend"
        state: started
        restart_policy: always
        published_ports:
          - "5000:5000"

    - name: Start frontend container
      docker_container:
        name: frontend
        image: "{{ docker_username }}/ecom-frontend"
        state: started
        restart_policy: always
        published_ports:
          - "3000:3000"
