name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecom-backend ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/ecom-backend

      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecom-frontend ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/ecom-frontend

      - name: Run Ansible Playbook to Deploy
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/deploy.yml
          inventory: ansible/inventory.ini
          key: ${{ secrets.EC2_SSH_KEY }}
          options: |
            -e docker_username=${{ secrets.DOCKER_USERNAME }}
